// GENERATED by scripts/export-abis.ts from contracts/hedera/out — minimal subset for now.
export const invoicePrimaryMarketAbi = [
  {
    type: 'function',
    name: 'buy',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'units', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'quote',
    stateMutability: 'view',
    inputs: [{ name: 'units', type: 'uint256' }],
    outputs: [{ name: 'costMicro', type: 'uint256' }],
  },
  {
    type: 'event',
    name: 'Purchased',
    inputs: [
      { name: 'investor', type: 'address', indexed: true },
      { name: 'units', type: 'uint256', indexed: false },
      { name: 'costMicro', type: 'uint256', indexed: false },
    ],
  },
] as const
