// GENERATED by scripts/export-abis.ts from contracts/sepolia/out — do not edit by hand.
// Minimal hand-written subset so the workspace typechecks before the first forge build.
export const verificationConsumerAbi = [
  {
    type: 'event',
    name: 'InvoiceVerified',
    inputs: [
      { name: 'businessLabel', type: 'string', indexed: false },
      { name: 'invoiceLabel', type: 'string', indexed: false },
      { name: 'invoiceHash', type: 'bytes32', indexed: true },
      { name: 'faceValueCents', type: 'uint256', indexed: false },
      { name: 'dueDate', type: 'uint64', indexed: false },
      { name: 'riskScore', type: 'uint16', indexed: false },
      { name: 'discountBps', type: 'uint16', indexed: false },
    ],
  },
  {
    type: 'function',
    name: 'onReport',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'metadata', type: 'bytes' },
      { name: 'report', type: 'bytes' },
    ],
    outputs: [],
  },
] as const
