/**
 * Copies ABIs from Foundry `out/` into packages/shared/src/abi/*.ts so web + adapter import
 * one typed source. Run after `forge build` in each contracts project:  pnpm abis
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs'
import { resolve } from 'node:path'

const jobs = [
  { out: 'contracts/sepolia/out/VerificationConsumer.sol/VerificationConsumer.json', dest: 'packages/shared/src/abi/verification-consumer.ts', name: 'verificationConsumerAbi' },
  { out: 'contracts/hedera/out/InvoicePrimaryMarket.sol/InvoicePrimaryMarket.json', dest: 'packages/shared/src/abi/invoice-primary-market.ts', name: 'invoicePrimaryMarketAbi' },
]

for (const j of jobs) {
  const src = resolve(j.out)
  if (!existsSync(src)) { console.warn(`skip (not built): ${j.out}`); continue }
  const { abi } = JSON.parse(readFileSync(src, 'utf8'))
  const body = `// GENERATED by scripts/export-abis.ts from ${j.out} — do not edit by hand.\nexport const ${j.name} = ${JSON.stringify(abi, null, 2)} as const\n`
  writeFileSync(resolve(j.dest), body)
  console.log(`wrote ${j.dest}`)
}
